CREATE TABLE IF NOT EXISTS `estandar5_evaluaciones_medicas_soportes` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `empresa_id` INT NOT NULL,
    `trabajador_id` INT NOT NULL,
    `evaluacion_id` INT DEFAULT NULL,
    `perfil_cargo_id` INT DEFAULT NULL,
    `centro_medico_id` INT DEFAULT NULL,
    `nombre_trabajador` VARCHAR(180) NOT NULL,
    `cedula` VARCHAR(40) NOT NULL,
    `cargo` VARCHAR(180) DEFAULT NULL,
    `tipo_examen` VARCHAR(80) DEFAULT NULL,
    `resultado` VARCHAR(120) DEFAULT NULL,
    `tipo_aptitud` VARCHAR(120) DEFAULT NULL,
    `centro_medico` VARCHAR(180) DEFAULT NULL,
    `fecha_expedicion` DATE DEFAULT NULL,
    `fecha_vencimiento` DATE DEFAULT NULL,
    `tiempo_para_programar` VARCHAR(80) DEFAULT NULL,
    `dias_accion` INT DEFAULT NULL,
    `altura_nivel_curso` VARCHAR(120) DEFAULT NULL,
    `altura_centro_capacitador` VARCHAR(180) DEFAULT NULL,
    `altura_fecha_expedicion` DATE DEFAULT NULL,
    `altura_fecha_vencimiento` DATE DEFAULT NULL,
    `altura_programar` VARCHAR(80) DEFAULT NULL,
    `altura_dias_accion` INT DEFAULT NULL,
    `confinado_nivel_curso` VARCHAR(120) DEFAULT NULL,
    `confinado_centro_capacitador` VARCHAR(180) DEFAULT NULL,
    `confinado_fecha_expedicion` DATE DEFAULT NULL,
    `confinado_fecha_vencimiento` DATE DEFAULT NULL,
    `confinado_programar` VARCHAR(80) DEFAULT NULL,
    `confinado_dias_accion` INT DEFAULT NULL,
    `archivo_pdf` VARCHAR(500) NOT NULL,
    `texto_extraido` LONGTEXT DEFAULT NULL,
    `observaciones` TEXT DEFAULT NULL,
    `creado_por` INT DEFAULT NULL,
    `creado_en` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `actualizado_en` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY `idx_e5_soporte_empresa` (`empresa_id`),
    KEY `idx_e5_soporte_trabajador` (`trabajador_id`),
    KEY `idx_e5_soporte_eval` (`evaluacion_id`),
    KEY `idx_e5_soporte_vencimiento` (`fecha_vencimiento`),
    KEY `idx_e5_soporte_altura_vencimiento` (`altura_fecha_vencimiento`),
    KEY `idx_e5_soporte_confinado_vencimiento` (`confinado_fecha_vencimiento`),
    CONSTRAINT `fk_e5_soporte_trabajador` FOREIGN KEY (`trabajador_id`)
        REFERENCES `usuarios` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_e5_soporte_eval` FOREIGN KEY (`evaluacion_id`)
        REFERENCES `estandar5_evaluaciones_medicas` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_e5_soporte_perfil` FOREIGN KEY (`perfil_cargo_id`)
        REFERENCES `estandar5_perfiles_cargo` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_e5_soporte_centro` FOREIGN KEY (`centro_medico_id`)
        REFERENCES `estandar5_centros_medicos` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_e5_soporte_creador` FOREIGN KEY (`creado_por`)
        REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
