CREATE TABLE IF NOT EXISTS demo_prospectos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre_completo VARCHAR(150) NOT NULL,
    empresa VARCHAR(180) NOT NULL,
    email VARCHAR(180) NOT NULL,
    telefono VARCHAR(40) NOT NULL,
    ciudad VARCHAR(100) NULL,
    cargo VARCHAR(120) NULL,
    cantidad_trabajadores INT UNSIGNED NOT NULL DEFAULT 1,
    interes VARCHAR(80) NOT NULL DEFAULT 'Plan PEM',
    estado VARCHAR(30) NOT NULL DEFAULT 'nuevo',
    notas TEXT NULL,
    origen VARCHAR(60) NOT NULL DEFAULT 'demo_pem',
    paginas_vistas INT UNSIGNED NOT NULL DEFAULT 0,
    primera_visita DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_visita DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    acepta_contacto TINYINT(1) NOT NULL DEFAULT 1,
    acceso_estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    acceso_token_hash CHAR(64) NULL,
    acceso_token_sufijo VARCHAR(12) NULL,
    acceso_generado_en DATETIME NULL,
    acceso_expira_en DATETIME NULL,
    acceso_revocado_en DATETIME NULL,
    acceso_decidido_en DATETIME NULL,
    acceso_decidido_por INT NULL,
    notificacion_enviada_en DATETIME NULL,
    notificacion_error VARCHAR(500) NULL,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_demo_prospectos_email (email),
    UNIQUE KEY uq_demo_prospectos_token (acceso_token_hash),
    KEY idx_demo_prospectos_estado (estado),
    KEY idx_demo_prospectos_acceso (acceso_estado, acceso_expira_en),
    KEY idx_demo_prospectos_ultima_visita (ultima_visita),
    KEY idx_demo_prospectos_creado_en (creado_en)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
