CREATE TABLE IF NOT EXISTS `estandar6_ipvr_registros` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `empresa_id` INT NOT NULL,
    `numero` INT NOT NULL,
    `sitio_trabajo` VARCHAR(180) DEFAULT NULL,
    `cuadro_basico` VARCHAR(180) DEFAULT NULL,
    `proceso` VARCHAR(180) NOT NULL,
    `actividad` VARCHAR(220) NOT NULL,
    `tarea` TEXT DEFAULT NULL,
    `zona_lugar` VARCHAR(180) DEFAULT NULL,
    `clase_actividad` ENUM('Rutinaria','No Rutinaria') NOT NULL DEFAULT 'Rutinaria',
    `origen_actividad` ENUM('Interna','Externa') NOT NULL DEFAULT 'Interna',
    `cargos` TEXT DEFAULT NULL,
    `directos` INT NOT NULL DEFAULT 0,
    `contratistas` INT NOT NULL DEFAULT 0,
    `visitantes` INT NOT NULL DEFAULT 0,
    `total_expuestos` INT NOT NULL DEFAULT 0,
    `peligro` VARCHAR(80) NOT NULL,
    `clasificacion_peligro` VARCHAR(180) NOT NULL,
    `metodologia_ref` VARCHAR(180) DEFAULT NULL,
    `descripcion_peligro` TEXT DEFAULT NULL,
    `categoria` ENUM('Salud','Seguridad','Propiedad_Proceso') NOT NULL DEFAULT 'Seguridad',
    `nivel_danio` VARCHAR(120) NOT NULL,
    `nivel_deficiencia` INT NOT NULL DEFAULT 2,
    `valoracion_nd` VARCHAR(80) DEFAULT NULL,
    `valoracion_nd_descripcion` TEXT DEFAULT NULL,
    `nivel_exposicion` INT NOT NULL DEFAULT 1,
    `nivel_probabilidad` INT NOT NULL DEFAULT 0,
    `interpretacion_probabilidad` VARCHAR(40) DEFAULT NULL,
    `nivel_consecuencia` INT NOT NULL DEFAULT 10,
    `nivel_riesgo` INT NOT NULL DEFAULT 0,
    `significado_riesgo` VARCHAR(180) DEFAULT NULL,
    `aceptabilidad` VARCHAR(120) DEFAULT NULL,
    `peor_consecuencia` VARCHAR(220) DEFAULT NULL,
    `requisito_legal` ENUM('SI','NO') NOT NULL DEFAULT 'NO',
    `control_fuente` TEXT DEFAULT NULL,
    `control_medio` TEXT DEFAULT NULL,
    `control_persona` TEXT DEFAULT NULL,
    `instrumento` TEXT DEFAULT NULL,
    `nivel_deficiencia_residual` INT NOT NULL DEFAULT 2,
    `nivel_exposicion_residual` INT NOT NULL DEFAULT 1,
    `nivel_probabilidad_residual` INT NOT NULL DEFAULT 0,
    `interpretacion_probabilidad_residual` VARCHAR(40) DEFAULT NULL,
    `nivel_consecuencia_residual` INT NOT NULL DEFAULT 10,
    `nivel_riesgo_residual` INT NOT NULL DEFAULT 0,
    `significado_riesgo_residual` VARCHAR(180) DEFAULT NULL,
    `aceptabilidad_residual` VARCHAR(120) DEFAULT NULL,
    `eliminacion` TEXT DEFAULT NULL,
    `sustitucion` TEXT DEFAULT NULL,
    `controles_ingenieria` TEXT DEFAULT NULL,
    `senalizacion_advertencia` TEXT DEFAULT NULL,
    `administrativos` TEXT DEFAULT NULL,
    `epp` TEXT DEFAULT NULL,
    `factor_reduccion` DECIMAL(6,2) NOT NULL DEFAULT 0,
    `accidentes_anterior` INT DEFAULT NULL,
    `accidentes_actual` INT DEFAULT NULL,
    `eficacia_controles` ENUM('SI','NO','') NOT NULL DEFAULT '',
    `observaciones` TEXT DEFAULT NULL,
    `creado_por` INT DEFAULT NULL,
    `creado_en` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `actualizado_en` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY `idx_e6_ipvr_empresa` (`empresa_id`),
    KEY `idx_e6_ipvr_numero` (`empresa_id`, `numero`),
    KEY `idx_e6_ipvr_peligro` (`peligro`),
    KEY `idx_e6_ipvr_riesgo` (`nivel_riesgo`),
    KEY `idx_e6_ipvr_riesgo_residual` (`nivel_riesgo_residual`),
    CONSTRAINT `fk_e6_ipvr_creador` FOREIGN KEY (`creado_por`)
        REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
